export const businessCategories = [
  {
    name: "Health & Wellness",
    businesses: [
      "Dentists",
      "Physicians (General Practice, Specialists)",
      "Chiropractors",
      "Physical Therapists",
      "Veterinarians",
      "Pharmacies",
      "Mental Health Counselors",
      "Optometrists/Eyewear Stores",
      "Fitness Centers/Gyms",
      "Yoga/Pilates Studios",
    ],
  },
  {
    name: "Professional Services",
    businesses: [
      "Accountants/Tax Preparers",
      "Lawyers/Legal Advisors",
      "Real Estate Agents/Brokers",
      "Insurance Agents",
      "Marketing/Advertising Agencies",
      "Consulting Firms (Business, IT, HR)",
      "Architects/Design Firms",
      "Engineering Firms",
    ],
  },
  {
    name: "Home Improvement & Maintenance",
    businesses: [
      "HVAC Contractors",
      "Roofing Contractors",
      "Plumbers",
      "Electricians",
      "Handyman Services",
      "Painters",
      "Flooring Specialists",
      "Window/Door Installers",
      "Landscaping Services",
      "Pest Control",
    ],
  },
  {
    name: "Retail",
    businesses: [
      "Clothing Boutiques",
      "Grocery Stores",
      "Hardware Stores",
      "Furniture Stores",
      "Bookstores",
      "Electronics Retailers",
      "Gift Shops",
      "Pet Supply Stores",
      "Liquor Stores",
      "Thrift/Vintage Shops",
    ],
  },
  {
    name: "Food & Beverage",
    businesses: [
      "Restaurants (Casual, Fine Dining)",
      "Cafés/Coffee Shops",
      "Bakeries",
      "Food Trucks",
      "Bars/Pubs",
      "Catering Services",
      "Specialty Food Stores (Butcher, Bakery, Deli)",
      "Wineries/Breweries",
    ],
  },
  {
    name: "Automotive",
    businesses: [
      "Auto Repair Shops",
      "Car Washes",
      "Dealerships (New/Used Cars)",
      "Auto Parts Stores",
      "Detailing Services",
      "Tire Shops",
      "Towing Services",
    ],
  },
  {
    name: "Personal Care",
    businesses: [
      "Hair Salons/Barbers",
      "Spas/Estheticians",
      "Nail Salons",
      "Tattoo/Piercing Studios",
      "Massage Therapists",
      "Cosmetic Retailers",
    ],
  },
  {
    name: "Education & Learning",
    businesses: [
      "Tutoring Centers",
      "Language Schools",
      "Music/Dance Lessons",
      "Preschools/Daycares",
      "Vocational Training",
      "Test Prep Services",
    ],
  },
  {
    name: "Technology & IT",
    businesses: [
      "IT Support Services",
      "Web Design/Development",
      "Cybersecurity Firms",
      "Software Companies",
      "Electronics Repair",
    ],
  },
  {
    name: "Financial Services",
    businesses: [
      "Banks/Credit Unions",
      "Financial Advisors",
      "Payday Loan Services",
      "Tax Preparation",
      "Investment Firms",
    ],
  },
  {
    name: "Construction & Trades",
    businesses: [
      "General Contractors",
      "Excavation Services",
      "Masonry/Concrete Work",
      "Carpentry/Cabinet Makers",
      "Welding/Fabrication",
    ],
  },
  {
    name: "Real Estate",
    businesses: ["Property Management", "Home Staging", "Real Estate Appraisers", "Title Companies"],
  },
  {
    name: "Hospitality & Entertainment",
    businesses: ["Hotels/Motels", "Event Venues", "Theaters/Cinemas", "Bowling Alleys", "Arcades/Gaming Centers"],
  },
  {
    name: "Environmental & Sustainability",
    businesses: [
      "Solar Panel Installers",
      "Recycling Centers",
      "Eco-Friendly Retailers",
      "Energy Efficiency Consultants",
    ],
  },
  {
    name: "Legal Services",
    businesses: ["Law Firms (Family, Corporate, Criminal)", "Notaries Public", "Mediation/Arbitration Services"],
  },
  {
    name: "Pet Services",
    businesses: ["Pet Groomers", "Pet Boarding/Kennels", "Dog Walkers/Trainers", "Pet Stores"],
  },
  {
    name: "Miscellaneous",
    businesses: [
      "Locksmiths",
      "Photographers/Videographers",
      "Event Planners",
      "Dry Cleaners/Laundromats",
      "Printing/Copy Shops",
      "Florists",
      "Courier/Delivery Services",
    ],
  },
]
